### ISSUE TITLE
Change Trainer permissions under the Profile tab

### ISSUE THREAD

**Issue by miguelcarloss** [revaturelabs/assignforce-client#211]
Trainers should be able to edit their:
- email
- resume
- skills 
- preferred location

A trainer should not be able to alter:
- addresses
- batches
- curricula
- skills
- other trainers
- their own active status

**Comment by MosesExe** [comment]
Preferred Location already functioning, added email, working on skills now

**Comment by MosesExe** [comment]
Removing ability to edit email because as it's implemented now it breaks the profile page since it's what's used to reference the whole thing

**Comment by MosesExe** [comment]
Trainers should be able to edit their:
email: If I enable this it disconnects profiles from users because it doesn't match the auth0 set up by that user
resume: Being implemented later
skills: Only SVP should have this power and at this time SVP does + stated in should not
preferred location: Can do this
A trainer should not be able to alter:

addresses
batches
curricula
skills
other trainers
their own active status
